version: 0.2
phases:
  build:
    commands:
      - ./gradlew clean bootJar
      - chmod +x scripts/*.sh || true
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/libs/*.jar
  discard-paths: no