version: 0.2

phases:
  pre_build:
    commands:
      - chmod +x ./gradlew
  build:
    commands:
      - cp appspec_ec2.yml appspec.yml
      - ./gradlew clean bootJar
      - ./gradlew -q properties | grep "^version:"
      - ls -al build/libs

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/libs/*.jar