version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 416225317325.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo "Building Spring Boot..."
      - chmod +x ./gradlew
      - ./gradlew clean build -x test
      - echo "Building Docker image..."
      # 변수를 쓰지 말고 이름을 직접 박으세요 (중요!)
      - docker build -t 416225317325.dkr.ecr.ap-southeast-1.amazonaws.com/ai0917-backend-springboot:latest .
  post_build:
    commands:
      - echo "Pushing to ECR..."
      - docker push 416225317325.dkr.ecr.ap-southeast-1.amazonaws.com/ai0917-backend-springboot:latest
      - echo "Updating Kubeconfig..."
      - aws eks update-kubeconfig --region ap-southeast-1 --name ai0917-backend-eks
      - echo "Applying Kubernetes Manifests..."
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl apply -f ingress.yaml
      - echo "Deployment completed."
      - printf '[{"name":"ai0917-backend","imageUri":"416225317325.dkr.ecr.ap-southeast-1.amazonaws.com/ai0917-backend-springboot:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json