version: 0.2

phases:
  pre_build:
    commands:
      - chmod +x ./gradlew
  build:
    commands:
      - ./gradlew clean build

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/libs/*.jar